;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2016/6/25 星期六 14:15:00

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1038	1038	; - - 下拉框.html
#define IDH_1000	1000	; 1.html 1.html
#define IDH_1001	1001	; 2.html 2.html
#define IDH_1003	1003	; 3d小球.html 3d小球.html
#define IDH_1004	1004	; angularJs学习.html angularJs学习.html
#define IDH_1064	1064	; autocomplete demo 浏览器搜索提示关键字.html
#define IDH_1005	1005	; before和after.html before和after.html
#define IDH_1035	1035	; Bootstrap 瀹炰緥 - 杞挱锛圕arousel锛夋彃浠剁殑鏍囬 xuanzhuan.html
#define IDH_1006	1006	; Bootstrap 瀹炰緥 - 妯℃�佹锛圡odal锛夋彃浠? bootstrap加载模态窗体.html
#define IDH_1011	1011	; ceshi.html ceshi.html
#define IDH_1066	1066	; Clear float 清除左浮动.html
#define IDH_1013	1013	; css3不断翻转.html css3不断翻转.html
#define IDH_1012	1012	; css3不断旋转.html css3不断旋转.html
#define IDH_1087	1087	; css3实现鼠标移上图片放大遮罩效果 - 素材家园 鼠标移上图片放大遮罩效果.html
#define IDH_1081	1081	; CSS3榧犳爣鎮仠鏄剧ず鍔ㄧ敾杈规-鏌箰涔? 边框动画.html
#define IDH_1015	1015	; ie兼容css3.html ie兼容css3.html
#define IDH_1016	1016	; index.html index.html
#define IDH_1042	1042	; jQuery UI 鍙嫋鍔ㄦā鎬佺獥浣? 可拖动模态窗体.html
#define IDH_1067	1067	; jQuery整屏（全屏）滚动插件 - 【懒人码库】 滚轮滚动一屏切换页面.html
#define IDH_1023	1023	; Js点击事件.html Js点击事件.html
#define IDH_1024	1024	; js自调用.html js自调用.html
#define IDH_1025	1025	; li.html li.html
#define IDH_1074	1074	; MyHtml.html 网页中弹出另一网页.html
#define IDH_1028	1028	; QQ授权测试 QQ授权登录.html
#define IDH_1058	1058	; QQ授权测试 新浪授权登录.html
#define IDH_1079	1079	; QQ授权测试 谷歌浏览器滚动条变细.html
#define IDH_1033	1033	; svg测试.html svg测试.html
#define IDH_1034	1034	; test1.html test1.html
#define IDH_1014	1014	; WEB楠囧DEMO - CSS animation 涓ょ鍔ㄧ敾鍚屾椂杩涜 css来回移动.html
#define IDH_1068	1068	; wheel 滚轮滚动切换页面.html
#define IDH_1071	1071	; 百度图片遮罩.html 百度图片遮罩.html
#define IDH_1075	1075	; 背景星星闪烁.html 背景星星闪烁.html
#define IDH_1076	1076	; 背景颜色不断变化加过渡.html 背景颜色不断变化加过渡.html
#define IDH_1063	1063	; 测试验证表单.html 测试验证表单.html
#define IDH_1056	1056	; 插件开发.html 插件开发.html
#define IDH_1070	1070	; 电商页面.html 电商页面.html
#define IDH_1073	1073	; 盾牌加飞剑.html 盾牌加飞剑.html
#define IDH_1051	1051	; 榧犳爣闀挎寜浜嬩欢 左键长按事件.html
#define IDH_1046	1046	; 复制 css3不断旋转.html 复制 css3不断旋转.html
#define IDH_1043	1043	; 各种基本图形.html 各种基本图形.html
#define IDH_1080	1080	; 购物车动画效果.html 购物车动画效果.html
#define IDH_1053	1053	; 寰俊JS-SDK Demo 微信授权登录.html
#define IDH_1069	1069	; 火狐画虚线圆.html 火狐画虚线圆.html
#define IDH_1048	1048	; 将jq函数封装和jq函数同级别调用.html 将jq函数封装和jq函数同级别调用.html
#define IDH_1047	1047	; 奖金调整.html 奖金调整.html
#define IDH_1049	1049	; 涓ぉ褰╃エ-棣栭〉 小球依次滚出来.html
#define IDH_1040	1040	; 克隆剪切.html 克隆剪切.html
#define IDH_1002	1002	; 轮播图 3.html
#define IDH_1084	1084	; 鎷栧姩楠岃瘉jquery鎻掍欢 随机生成验证码.html
#define IDH_1027	1027	; 美图WEB开放平台 meitu.html
#define IDH_1045	1045	; 鏂囦欢base64-鐩存帴鎷栬繘鏉? 图片转64为字符串.html
#define IDH_1041	1041	; 判断浏览器版本号.html 判断浏览器版本号.html
#define IDH_1052	1052	; 平移轮播.html 平移轮播.html
#define IDH_1055	1055	; 扑克翻牌效果.html 扑克翻牌效果.html
#define IDH_1037	1037	; 三角形.html 三角形.html
#define IDH_1060	1060	; 时间倒计时.html 时间倒计时.html
#define IDH_1039	1039	; 事件委托.html 事件委托.html
#define IDH_1077	1077	; 视差滚动.html 视差滚动.html
#define IDH_1054	1054	; 手机端滑动登陆.html 手机端滑动登陆.html
#define IDH_1050	1050	; 属性获值.html 属性获值.html
#define IDH_1085	1085	; 鼠标滑动登陆.html 鼠标滑动登陆.html
#define IDH_1089	1089	; 鼠标移动背景微动.html 鼠标移动背景微动.html
#define IDH_1088	1088	; 鼠标移动后文字飞来飞去.html 鼠标移动后文字飞来飞去.html
#define IDH_1086	1086	; 鼠标移上出现遮罩.html 鼠标移上出现遮罩.html
#define IDH_1057	1057	; 数组去重.html 数组去重.html
#define IDH_1083	1083	; 随机生成数字变化滚球.html 随机生成数字变化滚球.html
#define IDH_1065	1065	; 淘宝样式初始化.html 淘宝样式初始化.html
#define IDH_1078	1078	; 调用自定义插件的附加属性.html 调用自定义插件的附加属性.html
#define IDH_1044	1044	; 图片实现前loading.html 图片实现前loading.html
#define IDH_1036	1036	; 绾疛S鐪佸競鍖鸿仈鍔? 三级联动js版.html
#define IDH_1059	1059	; 无缝轮播.html 无缝轮播.html
#define IDH_1072	1072	; 浠跨櫨搴︽柊闂昏彍鍗曟粦鍔ㄥ姩鐢? 百度新闻导航背景滑动.html
#define IDH_1082	1082	; 选择标签的文本.html 选择标签的文本.html
#define IDH_1062	1062	; 正在开奖文字闪烁.html 正在开奖文字闪烁.html
#define IDH_1061	1061	; 妯℃嫙妯℃�佺獥鍙? 模拟模态窗体.html
#define IDH_1007	1007	; Responsive Nav &middot; Multiple Navigations Combined Demo bootstrap响应式导航\index.html
#define IDH_1009	1009	; canvas刚开始.html canvas学习中\canvas刚开始.html
#define IDH_1008	1008	; canvas七巧板.html canvas学习中\canvas七巧板.html
#define IDH_1010	1010	; canvas绚丽时钟倒计时.html canvas学习中\canvas绚丽时钟倒计时.html
#define IDH_1019	1019	; jQuery ios滚动条\index.html
#define IDH_1017	1017	; jQuery NiceScroll Browser Detection ios滚动条\browser.html
#define IDH_1022	1022	; 适用浏览器：360、FireFox、Chrome、Safari、Opera、傲游、搜狗、世界之窗. 不支持IE8及以下浏览器。 ios滚动条\说明.txt
#define IDH_1021	1021	; 中国站长站下载文件说明 ios滚动条\说明.htm
#define IDH_1018	1018	; GNU Lesser General Public License v3.0 - GNU Project - Free Software Foundation (FSF) ios滚动条\iframe\lgpl-3.0-standalone.html
#define IDH_1020	1020	; Original web page: http://jquery.org/license/ ios滚动条\js\jquery.license.txt
#define IDH_1026	1026	; 邢 唷?? lightbox\themes\default\images\a.txt
#define IDH_1029	1029	; SVG-edit svg学习中\svgEdit.html
#define IDH_1030	1030	; svgStudy.html svg学习中\svgStudy.html
#define IDH_1031	1031	; svg刚开始.html svg学习中\svg刚开始.html
#define IDH_1032	1032	; svg自定义属性替换.html svg学习中\svg自定义属性替换.html
